#!/usr/bin/perl -w
use strict;
open EST, "$ARGV[0]"||die "can not open $ARGV[0]\n";
open OUT, ">$ARGV[1]"||die "can not open $ARGV[1]\n";


my $rest="BM725712";

#>BM725712:NM_001384:Hs.324830:Noinfor:Noinfor
#CCCCACGGCCCCAGCTGGAGCTGGCTGAGAGCAGTCCTGCAGCCTCATTCCTTAGTTCCC
#GGAGCTGGCAAGGGCTGGAGCCCCGCCTGGGTCAGACGCCAGTGACAGAAGCTGTGAGTG
#GAAGACGAGGGATTGCCATCGCCTATGAGGATGAGGGAAGCGGCTGATACCATGTGGGGC
#TGGAGACATAGATGGACTTATGAATGGCTGCTAGGACCTTTAGTGCTCCCTGCACCAACC
#TCCCATCCCCCTGCCAAGATCCTTGAAGGACCCTGGAAGGAGGGAGAGCAGGCAGCCCTT
#CACAGGATAGGATCCGTCTCTGTCCTGTCCTGGCACTGGCACAAGCTCAGCACATGCCCA
#GTAATGCGTGTTGTTTGGCTGATGGAATAAAGGGCTTAGGGACTTCCCTGAGGCCTCTGG
#ACCCATCTGTCTTCCTGAGGGCAGCCCAGGACCTTTGGCCAATCCCAGTTCCCAGGCTGC
#AGTTTGAGGGTCTGTCCTTGTC
#>CA395126:NM_002794:Hs.471441:Noinfor:Noinfor
#CCCACTCGTCCGCTTATATAAGAATT
my $tag=0;
my $rest_seq;
while (my $line=<EST>) {
	
if ($line=~/>$rest/) {$tag=1;}
if ($tag==1) {$rest_seq.=$line;}
}

print OUT $rest_seq;