#!/usr/bin/perl -w

use strict;
use Getopt::Long;

open IN,"$ARGV[0]" || die"!";
open List,"$ARGV[1]" || die"!";

#NM_001024400_NM_001024400_scaffold_656_44975_45352.out
#ATCATCCGATCGCAGTTGCTGAAGGACCCCCAGGTGCTGTTTGCTGGATATAAGGTTCCTCATCCTCTGGAGCATAAGGTTGTGATCCGCGTTCAGACGACACCAGACTACAGTCCTCAGGAAG
#CCTTCACTAATGCCATCACGGATCTGATCAGTGAGCTGTCCCTGCTGGAGGAGCGATTTAGGGTTGCCATCAAAGACAAGCAGGAGGGGATAGAA
#GTGTCTGCAAGTCAGCTGTTGAAGGATCCTCAAGTTCTGTTTGCTGGGTACAAAGTTCCTCATCCTCTGGAACACAAGATCGTCATCAGAGTCCAGACGACACCTGACTACAGTCCACAGGAAG
#CCTTTACCAACGCCATCACTGACCTGATCAGCGAACTGTCTCTGCTGGAGGAACGTTTCCGCGTCGCCATTAAGGACAAACAGGAAGGGATTGAA
#
#NM_001003544_NM_001003544_scaffold_211_387073_388569.out
#TTTTTGTCGACATCGGTAATGAGACACGCGTCAGATGGACCTTCAAAATTCATCCCTCCGACCAAACCCGTTTTCACAGACAAATCACAAGAAGAGGCATCAGTCCGGGTTTTAAGTCCAGAGT
#TCATCCCTCCTCGCCAGCGCACTGACCAAATCAAGTTTTATATAGAACGGAAAGATATGATACAGAGGAGGAAAGTTTTGCAGATTCCAGAGTTTTACGTTAGCATTTTAGCAGTGACCATGAC
#AGATCCTTACGCGAGCGGGAACCTGAATCGCTTTGTTGGAATCTGCACTCAGCGCTCTGGAAAAGGATTGGGTGCTACTTTTATACTTAGGAATGTCATCGATGGGCAAGTAGAGATATGCTAT
#GAGCTGTACAGTCCACGTATGCGTAAGATTGAAGTGTTAAAGCTGGAGAAGAGACTGGATGACAATCTCATGTACTTGAGGGACGCTCTGCCTGAATACAGCACTTTTGACTTTGACATGCAAC
#CTGTCCATTATGAGCTCACGAAAGACATCCCAGTCAATCCGTTAAAAGTAAAAATGAAGCCAAAGCCGTGGTCTAAACGTTGGGAGCGCCCCAAGTTTGACATTAAGGGTATCCGCTTTGACCT
#GTATTTGACTCCAGAGCAGATGGAGCATGCGCAGAAGTGGGGAGAACCATGGAGAGAGTATGATATGCTAAAGGAGTATGACACATCCAGTCTAGAGAAGAAGATCCTTGAGGAGGTGGATGAA
#AATCTCAGAAAG

my %seq1;
my %seq2;
my $name;
while (<IN>) {
	chomp;
	my @infor=split;
	if (/_/) {
		$name=(split /\.out/,$_)[0];
		#print ">>>>>>>>>>>>>$name\n";
		next;
	}
	else
	{
		$seq1{$name}=$_;
		$_=<IN>;chomp;
		$seq2{$name}=$_;
		$_=<IN>;chomp;
	}
}
close IN;

#NM_213097       NM_213097_scaffold_415_151016_157914
#NM_001024400    NM_001024400_scaffold_656_44975_45352

my $T_seq1;my $T_seq2;
my $num;
while (<List>) {
	chomp;
	my @infor=split;
	$name="$infor[0]_$infor[1]";
	if (!exists $seq1{$name}) {next;}
	#print "$name\n";exit;
	$num++;
	$T_seq1.="$seq1{$name}";
	$T_seq2.="$seq2{$name}";
}

print ">seq1_$num\n$T_seq1\n>seq2\n$T_seq2\n";
